### ISSUE TITLE
SQL Dump File

### ISSUE THREAD

**Issue by eddeo93** [neight-allen/django-kickstarter-scraper#1]
Hi,

First of all, thank you so much for sharing this scraper. I am working on a research paper on crowdfunding and I need as much data as I can. However, my coding skills are limited, especially in python, django and SQL. I saw that you had a Kickscrape DB Dump with over 87,000+ projects. Can you please convert that into a .csv or excel file and share it with me? That will really make my life easier. Thank you so much.

Eddie

**Comment by neight-allen** [comment]
Try this: https://drive.google.com/open?id=0Bx11M2JmRNl5eHpRRUZ2ZEpta1U&authuser=2

I'm not totally sure what all is in it, but it's supposedly the dataset in csv. That link was posted to a blog that no longer exists.

**Comment by eddeo93** [comment]
You're a savior. Thank you so much!

**Comment by neight-allen** [comment]
🤘

**Comment by dragoon3** [comment]
@neight-allen Hi, I'm an undergraduate student from business school, recently we are dealing with a homework about data analysis about crowdfunding, I found the file you have uploaded one year ago and I really like your csv file with such more information. If you have time could you upload the latest csv dataset of kickstarter? It would be a great help, thank you so much
