### ISSUE TITLE
Would this still work today?

### ISSUE THREAD

**Issue by mrGreenbean** [neight-allen/django-kickstarter-scraper#2]
Hi there - This work is really quite amazing. The 87000 dataset is great! 

Just one thing - there are many projects in 2015 now. Is there any way to update the excel output so its got the latest projects? (I imagine there are nearly 200,000 now?) 

I'm writing a college term paper looking at crowdfunding - but still can't figure out how to get it to run.

**Comment by neight-allen** [comment]
Pretty doubtful that it would work today. Even when I was maintaining it,
it would fail every month or so as Kickstarter updated their site. You have
to tell it how to find the information on a project page, and a search
page, and a backers list, and so on. As long as you updated those files, it
could work.

I also don't have any intention of updating it. There are newer projects
out there to help scrape, but I don't know if anyone has an easy export to
excel, or if any even scrape the whole site out of the box.

Good luck with your paper.

**Comment by mrGreenbean** [comment]
Thank you for the response! 
Will see if the newer crawler works.

**Comment by mrGreenbean** [comment]
Sorry to bother you again - just got a quick followup, that I was hoping you might know.

Probably a long shot - did you have any csv more recent than the June 2013 csv (doesn't have to be anywhere near 2015) - looked around this weekend and it appears the detail in your dataset is among the best out there (there are 2009-2015 ones out there but they contain far less detail).

Have a good weekend,

**Comment by neight-allen** [comment]
Sorry, what's listed here is the latest.
